### ISSUE TITLE
API feedback

### ISSUE THREAD

**Issue by ianobermiller** [rofrischmann/inline-style-linter#11]
Have you thought about making the API more functional or less stateless? Having the linter be an object is nice if you want to precompute some things and cache them, but requiring methods be called in a specific order is poor DX. Instead of:

```js
const linter = new Linter(config)
linter.lint(styles)
const warnings = linter.getWarnings()
const stats = linter.generateStatistics()
linter.clear()
```

I propose:

```js
const linter = new Linter(config)
const {warnings, statistics} = linter.lint(styles)
```

That way, no state is stored in the instance and you can safely use it many times.

**Comment by rofrischmann** [comment]
@ianobermiller First of all thanks for your reply and help again :)
Hmm yeah, I get the point and also thought about that. I also could directly return both warnings and statistics but at some point it was nice to just run the linter all my Component tree down, and at one point (rootComponent) gather all the warnings and statistics together.

**Comment by rofrischmann** [comment]
I will actually only return the warnings as the statistics is something hardly storing any really useful information. If needed a user should be able to implement something like that without any problem at all.

**Comment by ianobermiller** [comment]
I see why you'd want to gather stats, but warnings probably require some extra metadata to identify them, such as the component or file name.

**Comment by rofrischmann** [comment]
Yeah, you're right. Actually (as the linter is for runtime usage) I am not aware of how to add the file name, but in Look I am using the linter warnings and add all additional information such as Component, element, etc. I will have a static to generate stats on the current basic level accepting a warnings array, but they should not be generated within the lint method itself.
